// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.wealth.noah.qa.entity;

import com.wealth.noah.qa.entity.TestCaseIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TestCaseIntegrationTest_Roo_Configurable {
    
    declare @type: TestCaseIntegrationTest: @Configurable;
    
}
