// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.wealth.noah.qa.entity;

import com.wealth.noah.qa.entity.TestSuitDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TestSuitDataOnDemand_Roo_Configurable {
    
    declare @type: TestSuitDataOnDemand: @Configurable;
    
}
